version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: node:20
    restart: unless-stopped
    working_dir: /app
    ports:
      - '5001:5001'
    volumes:
      - ./:/app
    command: bash -c "npm run start"
